export type {
  Consultation,
  ConsultationDashboard,
  ConsultationMeeting,
  ConsultationMessage,
  ConsultationQueue,
  ConsultationStatus,
  ConsultationSummary,
  ConsultationType,
  DoctorAvailabilityItem,
  DoctorConsultation,
  MeetingInput,
  MeetingProvider,
  MessageSenderRole,
  PatientClinicalRecord,
  PatientSummary,
  PatientVisit,
} from "@/shared/consultation/types/consultation";
